Eng 741
API-market/oreid-js pull request #118
Opened 2022-03-30 22:54 UTC by yardz

2022-03-30 23:55 UTC, traylewin requested changes
Great job! 
We need a little refactoring and cleanup before its finsihed.

2022-03-30 23:57 UTC, traylewin commented on package.json
> +  "version": "3.0.8-beta.0",
we already have a 3.0.8-beta.0 so bump to 3.0.8-beta.1

2022-03-31 18:17 UTC, traylewin commented on src/auth/auth.ts
> +  public subscribe(subscriber: SubscriberAuth) {
Yes I agree that works better. I assume this means making it an Interface

2022-03-31 20:20 UTC, WarrickFitz reviewed
Tray already reviewed. I did not have anything specific to add.

2022-03-31 20:20 UTC, WarrickFitz commented on src/index.ts
> +  User,
Show be addressed by the Linter

2022-03-31 20:23 UTC, yardz commented on src/index.ts
> +  User,
I've never seen lint for export, only for imports... But I fixed it.

2022-03-31 21:37 UTC, traylewin requested changes
Now that this code is reactive (using observables) I realized that we are missing something. The accessToken can expire but the Auth and User wouldn't know that. And the User.isLoggedIn() would report false results since it's using a static accessToken value.
SO I reworked the code to add:
AccessTokenHelper
- Extends Observable
- In setAccessToken() - sets a timer for the time that token expires like which clears accessToken and calls callSubscribers()
Auth
- subscribes to AccessTokenHelper
- when updated, callSubscribers() - which notifies User
User
- when updated, updates _accessToken, callSubscribers() 

All this will notify the React components when the token expires in real time
So user.isLoggedIn will change the moment the accessToken expires
All the code has been committed to this branch.
The easiest way to test this is to update the runAtTime function to expire the accessToken automatically after 5 seconds.

```
  /** Execute a callback function at a given Unix Epoch time */
  static runAtTime(callback: Function, executionEoochTime: number) {
    const now = Date.now()
    console.log('now:', now)
    executionEoochTime = now + 5000
    console.log('executionEoochTime:', executionEoochTime)
    const runAtTime = Math.max(executionEoochTime, now) // if executionEoochTime is in the past, use the current time to run the function immediately
    return setTimeout(callback, runAtTime - now)
  }
```

2022-03-31 21:37 UTC, traylewin commented on src/auth/auth.ts
> +    super.callSubscribers()
Make sure we callSubscribers() wherever we update data we care about in the class....
We are missing it after creating a new User (in get User()). Is there anywhere else missing?

2022-04-04 20:18 UTC, yardz commented
I just tested it and it worked. Can I merge?

@traylewin @WarrickFitz @deckb

2022-04-04 20:20 UTC, merged